apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-creds
  namespace: attendance-app
spec:
  encryptedData:
    .dockerconfigjson: AgCOLGqIMZsh3tzKKIU9XF5+6zREktx8MfgO2p4nkoFYIwoj80dgyzDovKZ9iPf2xomA9FWVMkTiuAIgyqDnw50kbrZCWTAYVfc0jprnmGsZMySHPmgB4tVn7D5AHAFT9plvG1J3jWVs9vmdb20ix4rZd3MII2PHeGA+I3/b+FF3NHIjEJ3JpGCktqBN63itVhV8uPe5MksuXBr7zKd8hdL7VwzeBiK7fRYsjaEJBoDVCoIlWA39y6yHhY2rWb0GFA6hH/xHO1Iuj23Y17OgsXsRRL8AxVqAyM28snLuOodHqoCeMEA9pM8qwGpnhQ5frf1AFHklcbgs6dhy9H9SRGX2zXqVKR99FiXPQJRzrP++z+jHXsfdw1gxMoYtbmkukcFg4a3R+Ps9ogz8vT+YhBsuKnbuI8VF2SdRYvTgcsaerUyb6fXs84gu1v0Z9Gd6nhy/l/cTBXoay31wIkVMRINXNyNa8K9KieQnSAv6ez73vx0hUmAKR6JMslp9do0vpNpfdeikU4q5FXa0ID4d+FPJV/eL1V25xzsVK3JKN3CgsuITVAqbJ9RAn21nr9t62lkY9RzNXJBGrw5d7/qkn/xNMgugGM2gBSIZ/S61xWj2OK/J6cfnpshAcNBMh8VoPm2GfH9ZGM8MfyfOTH6ZBCmtjSYIdbHACiN/GBew6Mj35r8GxMr2nnRzQg8aG1p9ncPoOcaEp6XOzVF1CTvvtQGXkiXUW8CyXUbRu6vDkMPjJ4+lDWNtD4dCnScrjhz3sc3rBDOnpjCKwcmAVYsIOurvK+xgumBNAd2eKGjqDJuPFAdUEPFTdrSs2LgPqXtjBFlmfUXj2yTLVgwq4ZU214mh+80CaP78R8YpnQ==
  template:
    metadata:
      name: docker-creds
      namespace: attendance-app
    type: kubernetes.io/dockerconfigjson