apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    DB_PASSWORD: {{ .Values.db.DB_PASSWORD }}
    DB_USER: {{ .Values.db.DB_USER }}
  template:
    metadata:
      name: {{ .Values.db.name }}
      namespace: {{ .Values.namespace }}