apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.docker.name }}
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.docker.dockerConfigjson }}
  template:
    metadata:
      name: {{ .Values.docker.name }}
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson